"""미국 주식/ETF 인기 종목 시드 (한국어 명칭).

yfinance에 전종목 리스트 API가 없어서, 약 300개를 하드코딩.
S&P 500 대형주 + 나스닥100 + 인기 ADR + 주요 ETF 위주.
"""
from __future__ import annotations

# (code, name(한글), market, asset_type)
US_SEEDS: list[tuple[str, str, str, str]] = [
    # ───────── 메가캡 테크 ─────────
    ("AAPL", "애플", "NASDAQ", "STOCK"),
    ("MSFT", "마이크로소프트", "NASDAQ", "STOCK"),
    ("NVDA", "엔비디아", "NASDAQ", "STOCK"),
    ("GOOGL", "알파벳 A (구글)", "NASDAQ", "STOCK"),
    ("GOOG", "알파벳 C (구글)", "NASDAQ", "STOCK"),
    ("AMZN", "아마존", "NASDAQ", "STOCK"),
    ("META", "메타 플랫폼스", "NASDAQ", "STOCK"),
    ("TSLA", "테슬라", "NASDAQ", "STOCK"),
    ("AVGO", "브로드컴", "NASDAQ", "STOCK"),
    ("ORCL", "오라클", "NYSE", "STOCK"),
    ("CRM", "세일즈포스", "NYSE", "STOCK"),
    ("ADBE", "어도비", "NASDAQ", "STOCK"),
    ("NFLX", "넷플릭스", "NASDAQ", "STOCK"),
    ("AMD", "AMD", "NASDAQ", "STOCK"),
    ("INTC", "인텔", "NASDAQ", "STOCK"),
    ("QCOM", "퀄컴", "NASDAQ", "STOCK"),
    ("CSCO", "시스코 시스템즈", "NASDAQ", "STOCK"),
    ("IBM", "IBM", "NYSE", "STOCK"),
    ("TXN", "텍사스 인스트루먼츠", "NASDAQ", "STOCK"),
    ("MU", "마이크론 테크놀로지", "NASDAQ", "STOCK"),
    ("ARM", "ARM 홀딩스", "NASDAQ", "STOCK"),
    ("PLTR", "팔란티어", "NYSE", "STOCK"),
    ("SHOP", "쇼피파이", "NYSE", "STOCK"),
    ("UBER", "우버", "NYSE", "STOCK"),
    ("LYFT", "리프트", "NASDAQ", "STOCK"),
    ("ABNB", "에어비앤비", "NASDAQ", "STOCK"),
    ("SNAP", "스냅", "NYSE", "STOCK"),
    ("PINS", "핀터레스트", "NYSE", "STOCK"),
    ("SPOT", "스포티파이", "NYSE", "STOCK"),
    ("RBLX", "로블록스", "NYSE", "STOCK"),
    ("U", "유니티 소프트웨어", "NYSE", "STOCK"),
    ("RDDT", "레딧", "NYSE", "STOCK"),
    ("EA", "일렉트로닉 아츠", "NASDAQ", "STOCK"),
    ("TTWO", "테이크투 인터랙티브", "NASDAQ", "STOCK"),
    ("MTCH", "매치 그룹 (틴더)", "NASDAQ", "STOCK"),
    ("BMBL", "범블", "NASDAQ", "STOCK"),
    ("DASH", "도어대시", "NYSE", "STOCK"),
    # 반도체 / 장비
    ("ASML", "ASML 홀딩", "NASDAQ", "STOCK"),
    ("TSM", "TSMC", "NYSE", "STOCK"),
    ("SMCI", "슈퍼마이크로 컴퓨터", "NASDAQ", "STOCK"),
    ("AMAT", "어플라이드 머티어리얼즈", "NASDAQ", "STOCK"),
    ("LRCX", "램 리서치", "NASDAQ", "STOCK"),
    ("KLAC", "KLA", "NASDAQ", "STOCK"),
    ("MRVL", "마벨 테크놀로지", "NASDAQ", "STOCK"),
    ("ON", "온세미컨덕터", "NASDAQ", "STOCK"),
    ("MCHP", "마이크로칩 테크놀로지", "NASDAQ", "STOCK"),
    ("SNPS", "시놉시스", "NASDAQ", "STOCK"),
    ("CDNS", "케이던스 디자인 시스템즈", "NASDAQ", "STOCK"),
    ("ANET", "아리스타 네트웍스", "NYSE", "STOCK"),
    ("WDC", "웨스턴 디지털", "NASDAQ", "STOCK"),
    ("STX", "씨게이트 테크놀로지", "NASDAQ", "STOCK"),
    # 소프트웨어 / 클라우드
    ("NOW", "서비스나우", "NYSE", "STOCK"),
    ("INTU", "인튜이트", "NASDAQ", "STOCK"),
    ("PANW", "팔로알토 네트웍스", "NASDAQ", "STOCK"),
    ("CRWD", "크라우드스트라이크", "NASDAQ", "STOCK"),
    ("ZS", "지스케일러", "NASDAQ", "STOCK"),
    ("FTNT", "포티넷", "NASDAQ", "STOCK"),
    ("OKTA", "옥타", "NASDAQ", "STOCK"),
    ("DDOG", "데이터독", "NASDAQ", "STOCK"),
    ("NET", "클라우드플레어", "NYSE", "STOCK"),
    ("MDB", "몽고DB", "NASDAQ", "STOCK"),
    ("SNOW", "스노우플레이크", "NYSE", "STOCK"),
    ("ZM", "줌 비디오", "NASDAQ", "STOCK"),
    ("DOCU", "도큐사인", "NASDAQ", "STOCK"),
    ("WDAY", "워크데이", "NASDAQ", "STOCK"),
    ("TEAM", "아틀라시안", "NASDAQ", "STOCK"),
    ("HUBS", "허브스팟", "NYSE", "STOCK"),
    ("AI", "C3.ai", "NYSE", "STOCK"),
    ("SOUN", "사운드하운드 AI", "NASDAQ", "STOCK"),
    ("PATH", "유아이패스", "NYSE", "STOCK"),
    ("IONQ", "아이온큐 (양자컴퓨팅)", "NYSE", "STOCK"),
    ("RGTI", "리게티 컴퓨팅", "NASDAQ", "STOCK"),
    # ───────── 금융 ─────────
    ("JPM", "JP모건 체이스", "NYSE", "STOCK"),
    ("BAC", "뱅크 오브 아메리카", "NYSE", "STOCK"),
    ("WFC", "웰스 파고", "NYSE", "STOCK"),
    ("C", "씨티그룹", "NYSE", "STOCK"),
    ("GS", "골드만 삭스", "NYSE", "STOCK"),
    ("MS", "모건 스탠리", "NYSE", "STOCK"),
    ("USB", "US 뱅코프", "NYSE", "STOCK"),
    ("PNC", "PNC 파이낸셜", "NYSE", "STOCK"),
    ("TFC", "트루이스트 파이낸셜", "NYSE", "STOCK"),
    ("COF", "캐피털 원", "NYSE", "STOCK"),
    ("V", "비자", "NYSE", "STOCK"),
    ("MA", "마스터카드", "NYSE", "STOCK"),
    ("AXP", "아메리칸 익스프레스", "NYSE", "STOCK"),
    ("DFS", "디스커버 파이낸셜", "NYSE", "STOCK"),
    ("PYPL", "페이팔", "NASDAQ", "STOCK"),
    ("SQ", "블록 (스퀘어)", "NYSE", "STOCK"),
    ("AFRM", "어펌", "NASDAQ", "STOCK"),
    ("SOFI", "소파이 테크놀로지스", "NASDAQ", "STOCK"),
    ("UPST", "업스타트 홀딩스", "NASDAQ", "STOCK"),
    ("BRK-B", "버크셔 해서웨이 B", "NYSE", "STOCK"),
    ("BLK", "블랙록", "NYSE", "STOCK"),
    ("BX", "블랙스톤", "NYSE", "STOCK"),
    ("KKR", "KKR", "NYSE", "STOCK"),
    ("APO", "아폴로 글로벌 매니지먼트", "NYSE", "STOCK"),
    ("SCHW", "찰스 슈왑", "NYSE", "STOCK"),
    ("COIN", "코인베이스", "NASDAQ", "STOCK"),
    ("HOOD", "로빈후드", "NASDAQ", "STOCK"),
    ("ICE", "ICE (인터컨티넨탈 익스체인지)", "NYSE", "STOCK"),
    ("CME", "CME 그룹", "NASDAQ", "STOCK"),
    ("NDAQ", "나스닥", "NASDAQ", "STOCK"),
    ("SPGI", "S&P 글로벌", "NYSE", "STOCK"),
    ("MCO", "무디스", "NYSE", "STOCK"),
    ("MMC", "마쉬 앤드 맥레넌", "NYSE", "STOCK"),
    ("AON", "에이온", "NYSE", "STOCK"),
    ("AIG", "AIG", "NYSE", "STOCK"),
    ("MET", "메트라이프", "NYSE", "STOCK"),
    ("PRU", "푸르덴셜 파이낸셜", "NYSE", "STOCK"),
    ("ALL", "올스테이트", "NYSE", "STOCK"),
    ("TRV", "트래블러스", "NYSE", "STOCK"),
    ("PGR", "프로그레시브", "NYSE", "STOCK"),
    # ───────── 헬스케어 ─────────
    ("LLY", "일라이 릴리", "NYSE", "STOCK"),
    ("UNH", "유나이티드헬스 그룹", "NYSE", "STOCK"),
    ("JNJ", "존슨 앤드 존슨", "NYSE", "STOCK"),
    ("PFE", "화이자", "NYSE", "STOCK"),
    ("MRK", "머크", "NYSE", "STOCK"),
    ("ABBV", "애브비", "NYSE", "STOCK"),
    ("NVO", "노보 노디스크", "NYSE", "STOCK"),
    ("ABT", "애보트 래버러토리스", "NYSE", "STOCK"),
    ("TMO", "써모 피셔 사이언티픽", "NYSE", "STOCK"),
    ("DHR", "다나허", "NYSE", "STOCK"),
    ("MDT", "메드트로닉", "NYSE", "STOCK"),
    ("BMY", "브리스톨 마이어스 스큅", "NYSE", "STOCK"),
    ("AMGN", "암젠", "NASDAQ", "STOCK"),
    ("GILD", "길리어드 사이언시스", "NASDAQ", "STOCK"),
    ("REGN", "리제너론", "NASDAQ", "STOCK"),
    ("VRTX", "버텍스 파마수티컬스", "NASDAQ", "STOCK"),
    ("BIIB", "바이오젠", "NASDAQ", "STOCK"),
    ("MRNA", "모더나", "NASDAQ", "STOCK"),
    ("BNTX", "바이오엔테크", "NASDAQ", "STOCK"),
    ("ISRG", "인튜이티브 서지컬", "NASDAQ", "STOCK"),
    ("SYK", "스트라이커", "NYSE", "STOCK"),
    ("BSX", "보스턴 사이언티픽", "NYSE", "STOCK"),
    ("EW", "에드워즈 라이프사이언시스", "NYSE", "STOCK"),
    ("ZBH", "짐머 바이오메트", "NYSE", "STOCK"),
    ("BDX", "벡톤 디킨슨", "NYSE", "STOCK"),
    ("ILMN", "일루미나", "NASDAQ", "STOCK"),
    ("IDXX", "아이덱스 래버러토리스", "NASDAQ", "STOCK"),
    ("ELV", "엘리번스 헬스", "NYSE", "STOCK"),
    ("CI", "시그나", "NYSE", "STOCK"),
    ("HUM", "휴매나", "NYSE", "STOCK"),
    ("CVS", "CVS 헬스", "NYSE", "STOCK"),
    ("WBA", "월그린스 부츠 얼라이언스", "NASDAQ", "STOCK"),
    ("HCA", "HCA 헬스케어", "NYSE", "STOCK"),
    # ───────── 소비재 / 리테일 ─────────
    ("WMT", "월마트", "NYSE", "STOCK"),
    ("COST", "코스트코", "NASDAQ", "STOCK"),
    ("HD", "홈디포", "NYSE", "STOCK"),
    ("LOW", "로우스", "NYSE", "STOCK"),
    ("TGT", "타겟", "NYSE", "STOCK"),
    ("DG", "달러 제너럴", "NYSE", "STOCK"),
    ("DLTR", "달러 트리", "NASDAQ", "STOCK"),
    ("TJX", "TJX 컴퍼니스", "NYSE", "STOCK"),
    ("ROST", "로스 스토어스", "NASDAQ", "STOCK"),
    ("ULTA", "얼타 뷰티", "NASDAQ", "STOCK"),
    ("LULU", "룰루레몬", "NASDAQ", "STOCK"),
    ("NKE", "나이키", "NYSE", "STOCK"),
    ("SBUX", "스타벅스", "NASDAQ", "STOCK"),
    ("MCD", "맥도날드", "NYSE", "STOCK"),
    ("CMG", "치폴레", "NYSE", "STOCK"),
    ("YUM", "얌 브랜즈", "NYSE", "STOCK"),
    ("DPZ", "도미노피자", "NYSE", "STOCK"),
    ("QSR", "레스토랑 브랜즈 (버거킹)", "NYSE", "STOCK"),
    ("DIS", "월트 디즈니", "NYSE", "STOCK"),
    ("KO", "코카콜라", "NYSE", "STOCK"),
    ("PEP", "펩시코", "NASDAQ", "STOCK"),
    ("PG", "프록터 앤드 갬블", "NYSE", "STOCK"),
    ("CL", "콜게이트 팜올리브", "NYSE", "STOCK"),
    ("KMB", "킴벌리 클라크", "NYSE", "STOCK"),
    ("EL", "에스티 로더", "NYSE", "STOCK"),
    ("MDLZ", "몬델리즈", "NASDAQ", "STOCK"),
    ("MO", "알트리아", "NYSE", "STOCK"),
    ("PM", "필립 모리스", "NYSE", "STOCK"),
    ("STZ", "콘스털레이션 브랜즈", "NYSE", "STOCK"),
    ("KHC", "크래프트 하인즈", "NASDAQ", "STOCK"),
    ("MNST", "몬스터 베버리지", "NASDAQ", "STOCK"),
    ("KDP", "큐리그 닥터페퍼", "NASDAQ", "STOCK"),
    ("BBY", "베스트 바이", "NYSE", "STOCK"),
    ("CVNA", "카바나", "NYSE", "STOCK"),
    ("KMX", "카맥스", "NYSE", "STOCK"),
    # ───────── 산업재 / 운송 ─────────
    ("BA", "보잉", "NYSE", "STOCK"),
    ("CAT", "캐터필러", "NYSE", "STOCK"),
    ("DE", "디어 (존디어)", "NYSE", "STOCK"),
    ("GE", "GE 에어로스페이스", "NYSE", "STOCK"),
    ("HON", "하니웰", "NASDAQ", "STOCK"),
    ("MMM", "3M", "NYSE", "STOCK"),
    ("LMT", "록히드 마틴", "NYSE", "STOCK"),
    ("RTX", "RTX (레이시언)", "NYSE", "STOCK"),
    ("NOC", "노스럽 그루먼", "NYSE", "STOCK"),
    ("GD", "제너럴 다이내믹스", "NYSE", "STOCK"),
    ("EMR", "에머슨 일렉트릭", "NYSE", "STOCK"),
    ("ETN", "이튼", "NYSE", "STOCK"),
    ("ITW", "일리노이 툴 웍스", "NYSE", "STOCK"),
    ("PH", "파커 하니핀", "NYSE", "STOCK"),
    ("UNP", "유니온 퍼시픽", "NYSE", "STOCK"),
    ("CSX", "CSX", "NASDAQ", "STOCK"),
    ("NSC", "노퍽 서던", "NYSE", "STOCK"),
    ("UPS", "UPS", "NYSE", "STOCK"),
    ("FDX", "페덱스", "NYSE", "STOCK"),
    ("LUV", "사우스웨스트 항공", "NYSE", "STOCK"),
    ("DAL", "델타 항공", "NYSE", "STOCK"),
    ("UAL", "유나이티드 항공", "NASDAQ", "STOCK"),
    ("AAL", "아메리칸 항공", "NASDAQ", "STOCK"),
    # ───────── 에너지 ─────────
    ("XOM", "엑손모빌", "NYSE", "STOCK"),
    ("CVX", "쉐브론", "NYSE", "STOCK"),
    ("COP", "코노코필립스", "NYSE", "STOCK"),
    ("EOG", "EOG 리소시즈", "NYSE", "STOCK"),
    ("OXY", "옥시덴탈 페트롤리움", "NYSE", "STOCK"),
    ("SLB", "슐럼버거", "NYSE", "STOCK"),
    ("MPC", "마라톤 페트롤리움", "NYSE", "STOCK"),
    ("PSX", "필립스 66", "NYSE", "STOCK"),
    ("VLO", "발레로 에너지", "NYSE", "STOCK"),
    ("KMI", "킨더 모건", "NYSE", "STOCK"),
    ("WMB", "윌리엄스 컴퍼니스", "NYSE", "STOCK"),
    ("ENPH", "엔페이즈 에너지", "NASDAQ", "STOCK"),
    ("FSLR", "퍼스트솔라", "NASDAQ", "STOCK"),
    # ───────── 자동차 / EV ─────────
    ("F", "포드 자동차", "NYSE", "STOCK"),
    ("GM", "제너럴 모터스", "NYSE", "STOCK"),
    ("STLA", "스텔란티스", "NYSE", "STOCK"),
    ("HMC", "혼다", "NYSE", "STOCK"),
    ("TM", "토요타", "NYSE", "STOCK"),
    ("RACE", "페라리", "NYSE", "STOCK"),
    ("RIVN", "리비안", "NASDAQ", "STOCK"),
    ("LCID", "루시드 그룹", "NASDAQ", "STOCK"),
    ("NIO", "니오", "NYSE", "STOCK"),
    ("XPEV", "샤오펑", "NYSE", "STOCK"),
    ("LI", "리오토", "NASDAQ", "STOCK"),
    ("BYDDY", "BYD ADR", "NASDAQ", "STOCK"),
    # ───────── 통신 / 미디어 ─────────
    ("T", "AT&T", "NYSE", "STOCK"),
    ("VZ", "버라이즌", "NYSE", "STOCK"),
    ("TMUS", "T모바일", "NASDAQ", "STOCK"),
    ("CMCSA", "컴캐스트", "NASDAQ", "STOCK"),
    ("CHTR", "차터 커뮤니케이션스", "NASDAQ", "STOCK"),
    ("WBD", "워너브라더스 디스커버리", "NASDAQ", "STOCK"),
    ("PARA", "파라마운트 글로벌", "NASDAQ", "STOCK"),
    # ───────── 유틸리티 ─────────
    ("NEE", "넥스트에라 에너지", "NYSE", "STOCK"),
    ("SO", "서던 컴퍼니", "NYSE", "STOCK"),
    ("DUK", "듀크 에너지", "NYSE", "STOCK"),
    ("AEP", "아메리칸 일렉트릭 파워", "NASDAQ", "STOCK"),
    # ───────── 부동산 REIT ─────────
    ("AMT", "아메리칸 타워", "NYSE", "STOCK"),
    ("PLD", "프로로지스", "NYSE", "STOCK"),
    ("EQIX", "에퀴닉스", "NASDAQ", "STOCK"),
    ("CCI", "크라운 캐슬", "NYSE", "STOCK"),
    ("PSA", "퍼블릭 스토리지", "NYSE", "STOCK"),
    ("O", "리얼티 인컴", "NYSE", "STOCK"),
    ("DLR", "디지털 리얼티 트러스트", "NYSE", "STOCK"),
    ("SPG", "사이먼 프로퍼티 그룹", "NYSE", "STOCK"),
    ("VICI", "VICI 프로퍼티스", "NYSE", "STOCK"),
    # ───────── 소재 / 광산 ─────────
    ("LIN", "린데", "NYSE", "STOCK"),
    ("APD", "에어 프로덕츠", "NYSE", "STOCK"),
    ("ECL", "에코랩", "NYSE", "STOCK"),
    ("SHW", "셔윈 윌리엄스", "NYSE", "STOCK"),
    ("FCX", "프리포트 맥모란", "NYSE", "STOCK"),
    ("NUE", "뉴코어", "NYSE", "STOCK"),
    ("CLF", "클리블랜드 클리프스", "NYSE", "STOCK"),
    ("AA", "알코아", "NYSE", "STOCK"),
    ("NEM", "뉴몬트 (금광)", "NYSE", "STOCK"),
    ("GOLD", "배릭 골드", "NYSE", "STOCK"),
    # ───────── 호텔 / 여행 / 게임 ─────────
    ("BKNG", "부킹홀딩스", "NASDAQ", "STOCK"),
    ("MAR", "메리어트 인터내셔널", "NASDAQ", "STOCK"),
    ("HLT", "힐튼 월드와이드", "NYSE", "STOCK"),
    ("RCL", "로열 캐리비안", "NYSE", "STOCK"),
    ("CCL", "카니발 크루즈", "NYSE", "STOCK"),
    ("NCLH", "노르웨이 크루즈 라인", "NYSE", "STOCK"),
    ("MGM", "MGM 리조트", "NYSE", "STOCK"),
    ("LVS", "라스베이거스 샌즈", "NYSE", "STOCK"),
    ("WYNN", "윈 리조트", "NASDAQ", "STOCK"),
    ("DKNG", "드래프트킹스", "NASDAQ", "STOCK"),
    # ───────── 중국 ADR ─────────
    ("BABA", "알리바바 그룹", "NYSE", "STOCK"),
    ("JD", "징둥닷컴", "NASDAQ", "STOCK"),
    ("PDD", "PDD 홀딩스 (테무)", "NASDAQ", "STOCK"),
    ("BIDU", "바이두", "NASDAQ", "STOCK"),
    ("NTES", "넷이즈", "NASDAQ", "STOCK"),
    ("BILI", "빌리빌리", "NASDAQ", "STOCK"),
    ("TCOM", "트립닷컴", "NASDAQ", "STOCK"),
    ("FUTU", "푸투 홀딩스", "NASDAQ", "STOCK"),
    ("TIGR", "타이거 브로커스", "NASDAQ", "STOCK"),
    # ───────── 유럽 / 기타 ADR ─────────
    ("SAP", "SAP", "NYSE", "STOCK"),
    ("NVS", "노바티스", "NYSE", "STOCK"),
    ("AZN", "아스트라제네카", "NASDAQ", "STOCK"),
    ("GSK", "GSK", "NYSE", "STOCK"),
    ("SNY", "사노피", "NASDAQ", "STOCK"),
    ("UL", "유니레버", "NYSE", "STOCK"),
    ("BP", "BP", "NYSE", "STOCK"),
    ("SHEL", "쉘", "NYSE", "STOCK"),
    ("TTE", "토탈에너지스", "NYSE", "STOCK"),
    ("RIO", "리오 틴토", "NYSE", "STOCK"),
    ("BHP", "BHP 그룹", "NYSE", "STOCK"),
    ("VALE", "발레", "NYSE", "STOCK"),
    # ───────── 한국 ADR ─────────
    ("KEP", "한국전력공사 ADR", "NYSE", "STOCK"),
    ("SHI", "SK Telecom (SHI) ADR", "NYSE", "STOCK"),
    ("KB", "KB금융 ADR", "NYSE", "STOCK"),
    ("WF", "우리금융 ADR", "NYSE", "STOCK"),
    ("SKM", "SK텔레콤 ADR", "NYSE", "STOCK"),
    ("LPL", "LG디스플레이 ADR", "NYSE", "STOCK"),
    # ───────── 일본 ADR ─────────
    ("SONY", "소니 그룹", "NYSE", "STOCK"),
    ("MUFG", "미쓰비시 UFJ", "NYSE", "STOCK"),
    ("MFG", "미즈호 파이낸셜", "NYSE", "STOCK"),
    ("SMFG", "스미토모 미쓰이", "NYSE", "STOCK"),
    ("NTT", "NTT", "NYSE", "STOCK"),
    # ───────── 밈주식 ─────────
    ("GME", "게임스탑", "NYSE", "STOCK"),
    ("AMC", "AMC 엔터테인먼트", "NYSE", "STOCK"),
    # ───────── 크립토 관련 ─────────
    ("MSTR", "마이크로스트래티지", "NASDAQ", "STOCK"),
    ("MARA", "마라톤 디지털", "NASDAQ", "STOCK"),
    ("RIOT", "라이엇 플랫폼스", "NASDAQ", "STOCK"),
    ("CLSK", "클린스파크", "NASDAQ", "STOCK"),
    ("HUT", "허트 8 마이닝", "NASDAQ", "STOCK"),
    ("BITF", "비트팜스", "NASDAQ", "STOCK"),
    ("IREN", "이리스 에너지", "NASDAQ", "STOCK"),
    ("WULF", "테라울프", "NASDAQ", "STOCK"),
    # ───────── ETF: 대표 지수 ─────────
    ("SPY", "SPDR S&P 500 ETF", "NYSE", "ETF"),
    ("QQQ", "인베스코 QQQ (나스닥100)", "NASDAQ", "ETF"),
    ("VOO", "뱅가드 S&P 500 ETF", "NYSE", "ETF"),
    ("IVV", "iShares 코어 S&P 500 ETF", "NYSE", "ETF"),
    ("VTI", "뱅가드 토탈 스톡마켓 ETF", "NYSE", "ETF"),
    ("DIA", "SPDR 다우존스 산업평균 ETF", "NYSE", "ETF"),
    ("IWM", "iShares 러셀 2000 ETF", "NYSE", "ETF"),
    ("MDY", "SPDR 미드캡 400 ETF", "NYSE", "ETF"),
    ("SPLG", "SPDR 포트폴리오 S&P 500 ETF", "NYSE", "ETF"),
    # ETF: 글로벌
    ("EFA", "iShares MSCI EAFE ETF (선진국)", "NYSE", "ETF"),
    ("VEA", "뱅가드 FTSE 선진국 ETF", "NYSE", "ETF"),
    ("VWO", "뱅가드 FTSE 신흥국 ETF", "NYSE", "ETF"),
    ("IEMG", "iShares 코어 신흥국 ETF", "NYSE", "ETF"),
    ("VT", "뱅가드 전세계 주식 ETF", "NYSE", "ETF"),
    ("ACWI", "iShares MSCI ACWI ETF", "NASDAQ", "ETF"),
    ("EWJ", "iShares MSCI 일본 ETF", "NYSE", "ETF"),
    ("EWY", "iShares MSCI 한국 ETF", "NYSE", "ETF"),
    ("EWT", "iShares MSCI 대만 ETF", "NYSE", "ETF"),
    ("INDA", "iShares MSCI 인도 ETF", "NASDAQ", "ETF"),
    ("FXI", "iShares 차이나 라지캡 ETF", "NASDAQ", "ETF"),
    ("MCHI", "iShares MSCI 차이나 ETF", "NASDAQ", "ETF"),
    ("KWEB", "크레인쉐어즈 차이나 인터넷 ETF", "NYSE", "ETF"),
    ("EWZ", "iShares MSCI 브라질 ETF", "NYSE", "ETF"),
    ("EWG", "iShares MSCI 독일 ETF", "NYSE", "ETF"),
    # ETF: 채권
    ("AGG", "iShares 미국채권총합 ETF", "NYSE", "ETF"),
    ("BND", "뱅가드 토탈본드 ETF", "NASDAQ", "ETF"),
    ("TLT", "iShares 미국 20년+ 국채 ETF", "NASDAQ", "ETF"),
    ("IEF", "iShares 미국 7-10년 국채 ETF", "NASDAQ", "ETF"),
    ("SHY", "iShares 미국 1-3년 국채 ETF", "NASDAQ", "ETF"),
    ("LQD", "iShares 투자등급 회사채 ETF", "NYSE", "ETF"),
    ("HYG", "iShares 하이일드 회사채 ETF", "NYSE", "ETF"),
    ("BIL", "SPDR 1-3개월 국채 ETF", "NYSE", "ETF"),
    # ETF: 원자재
    ("GLD", "SPDR 금 ETF", "NYSE", "ETF"),
    ("IAU", "iShares 골드 트러스트", "NYSE", "ETF"),
    ("SLV", "iShares 은 ETF", "NYSE", "ETF"),
    ("USO", "미국 원유 ETF", "NYSE", "ETF"),
    ("UNG", "미국 천연가스 ETF", "NYSE", "ETF"),
    ("DBC", "인베스코 원자재 ETF", "NYSE", "ETF"),
    # ETF: 섹터 (SPDR)
    ("XLK", "테크놀로지 섹터 SPDR", "NYSE", "ETF"),
    ("XLF", "금융 섹터 SPDR", "NYSE", "ETF"),
    ("XLE", "에너지 섹터 SPDR", "NYSE", "ETF"),
    ("XLV", "헬스케어 섹터 SPDR", "NYSE", "ETF"),
    ("XLY", "임의소비재 섹터 SPDR", "NYSE", "ETF"),
    ("XLP", "필수소비재 섹터 SPDR", "NYSE", "ETF"),
    ("XLI", "산업재 섹터 SPDR", "NYSE", "ETF"),
    ("XLU", "유틸리티 섹터 SPDR", "NYSE", "ETF"),
    ("XLB", "소재 섹터 SPDR", "NYSE", "ETF"),
    ("XLRE", "부동산 섹터 SPDR", "NYSE", "ETF"),
    ("XLC", "커뮤니케이션 섹터 SPDR", "NYSE", "ETF"),
    # ETF: 테마 / 성장
    ("SCHD", "슈왑 미국 배당주 ETF", "NYSE", "ETF"),
    ("VYM", "뱅가드 고배당 ETF", "NYSE", "ETF"),
    ("VIG", "뱅가드 배당성장 ETF", "NYSE", "ETF"),
    ("JEPI", "JP모건 에쿼티 프리미엄 인컴 ETF", "NYSE", "ETF"),
    ("JEPQ", "JP모건 나스닥 프리미엄 인컴 ETF", "NASDAQ", "ETF"),
    ("ARKK", "ARK 이노베이션 ETF", "NYSE", "ETF"),
    ("ARKW", "ARK 차세대 인터넷 ETF", "NYSE", "ETF"),
    ("ARKG", "ARK 게놈 혁명 ETF", "NYSE", "ETF"),
    ("ARKQ", "ARK 자율주행·로보틱스 ETF", "NYSE", "ETF"),
    ("ARKF", "ARK 핀테크 이노베이션 ETF", "NYSE", "ETF"),
    ("SOXX", "iShares 반도체 ETF", "NASDAQ", "ETF"),
    ("SMH", "VanEck 반도체 ETF", "NASDAQ", "ETF"),
    ("LIT", "글로벌X 리튬·배터리 ETF", "NYSE", "ETF"),
    ("URA", "글로벌X 우라늄 ETF", "NYSE", "ETF"),
    ("TAN", "인베스코 솔라 ETF", "NYSE", "ETF"),
    ("ICLN", "iShares 글로벌 청정에너지 ETF", "NASDAQ", "ETF"),
    ("GDX", "VanEck 골드마이너스 ETF", "NYSE", "ETF"),
    ("GDXJ", "VanEck 주니어 골드마이너스 ETF", "NYSE", "ETF"),
    # ETF: 레버리지 / 인버스
    ("TQQQ", "프로셰어스 3X 나스닥100 (TQQQ)", "NASDAQ", "ETF"),
    ("SQQQ", "프로셰어스 -3X 나스닥100 (SQQQ)", "NASDAQ", "ETF"),
    ("SOXL", "디렉시온 3X 반도체 불 (SOXL)", "NYSE", "ETF"),
    ("SOXS", "디렉시온 3X 반도체 베어 (SOXS)", "NYSE", "ETF"),
    ("SPXL", "디렉시온 3X S&P500 불", "NYSE", "ETF"),
    ("UPRO", "프로셰어스 3X S&P500", "NYSE", "ETF"),
    ("TMF", "디렉시온 3X 20년 국채 불", "NYSE", "ETF"),
    ("UVXY", "프로셰어스 1.5X VIX 단기", "NYSE", "ETF"),
    # ETF: 비트코인/이더리움
    ("IBIT", "iShares 비트코인 신탁 ETF", "NASDAQ", "ETF"),
    ("FBTC", "피델리티 비트코인 ETF", "NYSE", "ETF"),
    ("BITO", "프로셰어스 비트코인 ETF", "NYSE", "ETF"),
    ("ETHA", "iShares 이더리움 트러스트", "NASDAQ", "ETF"),
    ("GBTC", "그레이스케일 비트코인 트러스트", "NYSE", "ETF"),
    # ETF: 스타일
    ("VUG", "뱅가드 성장주 ETF", "NYSE", "ETF"),
    ("VTV", "뱅가드 가치주 ETF", "NYSE", "ETF"),
    ("MTUM", "iShares 모멘텀 ETF", "NASDAQ", "ETF"),
    ("USMV", "iShares 최소변동성 ETF", "NASDAQ", "ETF"),
    ("QUAL", "iShares 퀄리티 팩터 ETF", "NASDAQ", "ETF"),
    ("VNQ", "뱅가드 부동산 ETF", "NYSE", "ETF"),
]
