"""미국 주식/ETF 인기 종목 시드.

yfinance에 전종목 리스트 API가 없어서, 자주 거래되는 종목 ~150개를 하드코딩.
필요한 종목이 더 있으면 여기 추가하거나, 향후 검색 시 on-demand로 yfinance 조회 후 DB upsert.
"""
from __future__ import annotations

# (code, name, market, asset_type)
US_SEEDS: list[tuple[str, str, str, str]] = [
    # Mega cap tech
    ("AAPL", "Apple Inc.", "NASDAQ", "STOCK"),
    ("MSFT", "Microsoft Corporation", "NASDAQ", "STOCK"),
    ("NVDA", "NVIDIA Corporation", "NASDAQ", "STOCK"),
    ("GOOGL", "Alphabet Inc. Class A", "NASDAQ", "STOCK"),
    ("GOOG", "Alphabet Inc. Class C", "NASDAQ", "STOCK"),
    ("AMZN", "Amazon.com Inc.", "NASDAQ", "STOCK"),
    ("META", "Meta Platforms Inc.", "NASDAQ", "STOCK"),
    ("TSLA", "Tesla Inc.", "NASDAQ", "STOCK"),
    ("AVGO", "Broadcom Inc.", "NASDAQ", "STOCK"),
    ("ORCL", "Oracle Corporation", "NYSE", "STOCK"),
    ("CRM", "Salesforce Inc.", "NYSE", "STOCK"),
    ("ADBE", "Adobe Inc.", "NASDAQ", "STOCK"),
    ("NFLX", "Netflix Inc.", "NASDAQ", "STOCK"),
    ("AMD", "Advanced Micro Devices Inc.", "NASDAQ", "STOCK"),
    ("INTC", "Intel Corporation", "NASDAQ", "STOCK"),
    ("QCOM", "QUALCOMM Incorporated", "NASDAQ", "STOCK"),
    ("CSCO", "Cisco Systems Inc.", "NASDAQ", "STOCK"),
    ("IBM", "International Business Machines", "NYSE", "STOCK"),
    ("TXN", "Texas Instruments", "NASDAQ", "STOCK"),
    ("MU", "Micron Technology", "NASDAQ", "STOCK"),
    ("ARM", "Arm Holdings", "NASDAQ", "STOCK"),
    ("PLTR", "Palantir Technologies", "NYSE", "STOCK"),
    ("SHOP", "Shopify Inc.", "NYSE", "STOCK"),
    ("UBER", "Uber Technologies", "NYSE", "STOCK"),
    ("ABNB", "Airbnb Inc.", "NASDAQ", "STOCK"),
    ("SNAP", "Snap Inc.", "NYSE", "STOCK"),
    ("PINS", "Pinterest Inc.", "NYSE", "STOCK"),
    ("SPOT", "Spotify Technology", "NYSE", "STOCK"),
    ("RBLX", "Roblox Corporation", "NYSE", "STOCK"),
    ("U", "Unity Software", "NYSE", "STOCK"),
    # Finance
    ("JPM", "JPMorgan Chase", "NYSE", "STOCK"),
    ("BAC", "Bank of America", "NYSE", "STOCK"),
    ("WFC", "Wells Fargo", "NYSE", "STOCK"),
    ("GS", "Goldman Sachs", "NYSE", "STOCK"),
    ("MS", "Morgan Stanley", "NYSE", "STOCK"),
    ("V", "Visa Inc.", "NYSE", "STOCK"),
    ("MA", "Mastercard Inc.", "NYSE", "STOCK"),
    ("AXP", "American Express", "NYSE", "STOCK"),
    ("BRK-B", "Berkshire Hathaway", "NYSE", "STOCK"),
    ("BLK", "BlackRock Inc.", "NYSE", "STOCK"),
    ("PYPL", "PayPal Holdings", "NASDAQ", "STOCK"),
    ("SCHW", "Charles Schwab", "NYSE", "STOCK"),
    ("COIN", "Coinbase Global", "NASDAQ", "STOCK"),
    ("HOOD", "Robinhood Markets", "NASDAQ", "STOCK"),
    # Consumer / Retail
    ("WMT", "Walmart Inc.", "NYSE", "STOCK"),
    ("COST", "Costco Wholesale", "NASDAQ", "STOCK"),
    ("HD", "Home Depot", "NYSE", "STOCK"),
    ("LOW", "Lowe's Companies", "NYSE", "STOCK"),
    ("NKE", "Nike Inc.", "NYSE", "STOCK"),
    ("SBUX", "Starbucks Corporation", "NASDAQ", "STOCK"),
    ("MCD", "McDonald's Corporation", "NYSE", "STOCK"),
    ("DIS", "The Walt Disney Company", "NYSE", "STOCK"),
    ("KO", "Coca-Cola Company", "NYSE", "STOCK"),
    ("PEP", "PepsiCo Inc.", "NASDAQ", "STOCK"),
    ("PG", "Procter & Gamble", "NYSE", "STOCK"),
    # Health
    ("LLY", "Eli Lilly", "NYSE", "STOCK"),
    ("UNH", "UnitedHealth Group", "NYSE", "STOCK"),
    ("JNJ", "Johnson & Johnson", "NYSE", "STOCK"),
    ("PFE", "Pfizer Inc.", "NYSE", "STOCK"),
    ("MRK", "Merck & Co.", "NYSE", "STOCK"),
    ("ABBV", "AbbVie Inc.", "NYSE", "STOCK"),
    ("NVO", "Novo Nordisk", "NYSE", "STOCK"),
    # Industrial / Energy
    ("BA", "Boeing Company", "NYSE", "STOCK"),
    ("CAT", "Caterpillar Inc.", "NYSE", "STOCK"),
    ("GE", "General Electric", "NYSE", "STOCK"),
    ("XOM", "Exxon Mobil", "NYSE", "STOCK"),
    ("CVX", "Chevron Corporation", "NYSE", "STOCK"),
    ("OXY", "Occidental Petroleum", "NYSE", "STOCK"),
    # Auto / EV
    ("F", "Ford Motor Company", "NYSE", "STOCK"),
    ("GM", "General Motors", "NYSE", "STOCK"),
    ("RIVN", "Rivian Automotive", "NASDAQ", "STOCK"),
    ("LCID", "Lucid Group", "NASDAQ", "STOCK"),
    ("NIO", "NIO Inc.", "NYSE", "STOCK"),
    ("XPEV", "XPeng Inc.", "NYSE", "STOCK"),
    ("LI", "Li Auto", "NASDAQ", "STOCK"),
    # Misc popular
    ("BABA", "Alibaba Group", "NYSE", "STOCK"),
    ("JD", "JD.com Inc.", "NASDAQ", "STOCK"),
    ("PDD", "PDD Holdings", "NASDAQ", "STOCK"),
    ("TSM", "Taiwan Semiconductor", "NYSE", "STOCK"),
    ("ASML", "ASML Holding", "NASDAQ", "STOCK"),
    ("SMCI", "Super Micro Computer", "NASDAQ", "STOCK"),
    ("MSTR", "MicroStrategy", "NASDAQ", "STOCK"),
    ("MARA", "Marathon Digital", "NASDAQ", "STOCK"),
    ("RIOT", "Riot Platforms", "NASDAQ", "STOCK"),
    ("GME", "GameStop Corp.", "NYSE", "STOCK"),
    ("AMC", "AMC Entertainment", "NYSE", "STOCK"),
    # Major ETFs
    ("SPY", "SPDR S&P 500 ETF Trust", "NYSE", "ETF"),
    ("QQQ", "Invesco QQQ Trust", "NASDAQ", "ETF"),
    ("VOO", "Vanguard S&P 500 ETF", "NYSE", "ETF"),
    ("VTI", "Vanguard Total Stock Market ETF", "NYSE", "ETF"),
    ("IVV", "iShares Core S&P 500 ETF", "NYSE", "ETF"),
    ("DIA", "SPDR Dow Jones Industrial Average ETF", "NYSE", "ETF"),
    ("IWM", "iShares Russell 2000 ETF", "NYSE", "ETF"),
    ("EFA", "iShares MSCI EAFE ETF", "NYSE", "ETF"),
    ("VEA", "Vanguard FTSE Developed Markets ETF", "NYSE", "ETF"),
    ("VWO", "Vanguard FTSE Emerging Markets ETF", "NYSE", "ETF"),
    ("AGG", "iShares Core US Aggregate Bond ETF", "NYSE", "ETF"),
    ("BND", "Vanguard Total Bond Market ETF", "NASDAQ", "ETF"),
    ("TLT", "iShares 20+ Year Treasury Bond ETF", "NASDAQ", "ETF"),
    ("GLD", "SPDR Gold Shares", "NYSE", "ETF"),
    ("SLV", "iShares Silver Trust", "NYSE", "ETF"),
    ("USO", "United States Oil Fund", "NYSE", "ETF"),
    ("XLK", "Technology Select Sector SPDR", "NYSE", "ETF"),
    ("XLF", "Financial Select Sector SPDR", "NYSE", "ETF"),
    ("XLE", "Energy Select Sector SPDR", "NYSE", "ETF"),
    ("XLV", "Health Care Select Sector SPDR", "NYSE", "ETF"),
    ("XLY", "Consumer Discretionary Select Sector SPDR", "NYSE", "ETF"),
    ("XLP", "Consumer Staples Select Sector SPDR", "NYSE", "ETF"),
    ("XLI", "Industrial Select Sector SPDR", "NYSE", "ETF"),
    ("XLU", "Utilities Select Sector SPDR", "NYSE", "ETF"),
    ("XLB", "Materials Select Sector SPDR", "NYSE", "ETF"),
    ("XLRE", "Real Estate Select Sector SPDR", "NYSE", "ETF"),
    ("SCHD", "Schwab US Dividend Equity ETF", "NYSE", "ETF"),
    ("VYM", "Vanguard High Dividend Yield ETF", "NYSE", "ETF"),
    ("ARKK", "ARK Innovation ETF", "NYSE", "ETF"),
    ("SOXX", "iShares Semiconductor ETF", "NASDAQ", "ETF"),
    ("SMH", "VanEck Semiconductor ETF", "NASDAQ", "ETF"),
    ("IBIT", "iShares Bitcoin Trust ETF", "NASDAQ", "ETF"),
    ("FBTC", "Fidelity Wise Origin Bitcoin Fund", "NYSE", "ETF"),
]
