"""미국 주식/ETF 인기 종목 시드 (한국어 명칭).

yfinance에 전종목 리스트 API가 없어서, 자주 거래되는 종목 ~130개를 하드코딩.
종목명은 한국 투자자에게 친숙한 한글 표기로.
"""
from __future__ import annotations

# (code, name(한글), market, asset_type)
US_SEEDS: list[tuple[str, str, str, str]] = [
    # Mega cap tech
    ("AAPL", "애플", "NASDAQ", "STOCK"),
    ("MSFT", "마이크로소프트", "NASDAQ", "STOCK"),
    ("NVDA", "엔비디아", "NASDAQ", "STOCK"),
    ("GOOGL", "알파벳 A", "NASDAQ", "STOCK"),
    ("GOOG", "알파벳 C", "NASDAQ", "STOCK"),
    ("AMZN", "아마존", "NASDAQ", "STOCK"),
    ("META", "메타 플랫폼스", "NASDAQ", "STOCK"),
    ("TSLA", "테슬라", "NASDAQ", "STOCK"),
    ("AVGO", "브로드컴", "NASDAQ", "STOCK"),
    ("ORCL", "오라클", "NYSE", "STOCK"),
    ("CRM", "세일즈포스", "NYSE", "STOCK"),
    ("ADBE", "어도비", "NASDAQ", "STOCK"),
    ("NFLX", "넷플릭스", "NASDAQ", "STOCK"),
    ("AMD", "AMD", "NASDAQ", "STOCK"),
    ("INTC", "인텔", "NASDAQ", "STOCK"),
    ("QCOM", "퀄컴", "NASDAQ", "STOCK"),
    ("CSCO", "시스코 시스템즈", "NASDAQ", "STOCK"),
    ("IBM", "IBM", "NYSE", "STOCK"),
    ("TXN", "텍사스 인스트루먼츠", "NASDAQ", "STOCK"),
    ("MU", "마이크론 테크놀로지", "NASDAQ", "STOCK"),
    ("ARM", "ARM 홀딩스", "NASDAQ", "STOCK"),
    ("PLTR", "팔란티어", "NYSE", "STOCK"),
    ("SHOP", "쇼피파이", "NYSE", "STOCK"),
    ("UBER", "우버", "NYSE", "STOCK"),
    ("ABNB", "에어비앤비", "NASDAQ", "STOCK"),
    ("SNAP", "스냅", "NYSE", "STOCK"),
    ("PINS", "핀터레스트", "NYSE", "STOCK"),
    ("SPOT", "스포티파이", "NYSE", "STOCK"),
    ("RBLX", "로블록스", "NYSE", "STOCK"),
    ("U", "유니티 소프트웨어", "NYSE", "STOCK"),
    # Finance
    ("JPM", "JP모건 체이스", "NYSE", "STOCK"),
    ("BAC", "뱅크 오브 아메리카", "NYSE", "STOCK"),
    ("WFC", "웰스 파고", "NYSE", "STOCK"),
    ("GS", "골드만 삭스", "NYSE", "STOCK"),
    ("MS", "모건 스탠리", "NYSE", "STOCK"),
    ("V", "비자", "NYSE", "STOCK"),
    ("MA", "마스터카드", "NYSE", "STOCK"),
    ("AXP", "아메리칸 익스프레스", "NYSE", "STOCK"),
    ("BRK-B", "버크셔 해서웨이 B", "NYSE", "STOCK"),
    ("BLK", "블랙록", "NYSE", "STOCK"),
    ("PYPL", "페이팔", "NASDAQ", "STOCK"),
    ("SCHW", "찰스 슈왑", "NYSE", "STOCK"),
    ("COIN", "코인베이스", "NASDAQ", "STOCK"),
    ("HOOD", "로빈후드", "NASDAQ", "STOCK"),
    # Consumer / Retail
    ("WMT", "월마트", "NYSE", "STOCK"),
    ("COST", "코스트코", "NASDAQ", "STOCK"),
    ("HD", "홈디포", "NYSE", "STOCK"),
    ("LOW", "로우스", "NYSE", "STOCK"),
    ("NKE", "나이키", "NYSE", "STOCK"),
    ("SBUX", "스타벅스", "NASDAQ", "STOCK"),
    ("MCD", "맥도날드", "NYSE", "STOCK"),
    ("DIS", "월트 디즈니", "NYSE", "STOCK"),
    ("KO", "코카콜라", "NYSE", "STOCK"),
    ("PEP", "펩시코", "NASDAQ", "STOCK"),
    ("PG", "프록터 앤드 갬블", "NYSE", "STOCK"),
    # Health
    ("LLY", "일라이 릴리", "NYSE", "STOCK"),
    ("UNH", "유나이티드헬스 그룹", "NYSE", "STOCK"),
    ("JNJ", "존슨 앤드 존슨", "NYSE", "STOCK"),
    ("PFE", "화이자", "NYSE", "STOCK"),
    ("MRK", "머크", "NYSE", "STOCK"),
    ("ABBV", "애브비", "NYSE", "STOCK"),
    ("NVO", "노보 노디스크", "NYSE", "STOCK"),
    # Industrial / Energy
    ("BA", "보잉", "NYSE", "STOCK"),
    ("CAT", "캐터필러", "NYSE", "STOCK"),
    ("GE", "GE 에어로스페이스", "NYSE", "STOCK"),
    ("XOM", "엑손모빌", "NYSE", "STOCK"),
    ("CVX", "쉐브론", "NYSE", "STOCK"),
    ("OXY", "옥시덴탈 페트롤리움", "NYSE", "STOCK"),
    # Auto / EV
    ("F", "포드 자동차", "NYSE", "STOCK"),
    ("GM", "제너럴 모터스", "NYSE", "STOCK"),
    ("RIVN", "리비안", "NASDAQ", "STOCK"),
    ("LCID", "루시드 그룹", "NASDAQ", "STOCK"),
    ("NIO", "니오", "NYSE", "STOCK"),
    ("XPEV", "샤오펑", "NYSE", "STOCK"),
    ("LI", "리오토", "NASDAQ", "STOCK"),
    # Misc popular
    ("BABA", "알리바바 그룹", "NYSE", "STOCK"),
    ("JD", "징둥닷컴", "NASDAQ", "STOCK"),
    ("PDD", "PDD 홀딩스 (테무)", "NASDAQ", "STOCK"),
    ("TSM", "TSMC", "NYSE", "STOCK"),
    ("ASML", "ASML 홀딩", "NASDAQ", "STOCK"),
    ("SMCI", "슈퍼마이크로 컴퓨터", "NASDAQ", "STOCK"),
    ("MSTR", "마이크로스트래티지", "NASDAQ", "STOCK"),
    ("MARA", "마라톤 디지털", "NASDAQ", "STOCK"),
    ("RIOT", "라이엇 플랫폼스", "NASDAQ", "STOCK"),
    ("GME", "게임스탑", "NYSE", "STOCK"),
    ("AMC", "AMC 엔터테인먼트", "NYSE", "STOCK"),
    # Major ETFs
    ("SPY", "SPDR S&P 500 ETF", "NYSE", "ETF"),
    ("QQQ", "인베스코 QQQ (나스닥100)", "NASDAQ", "ETF"),
    ("VOO", "뱅가드 S&P 500 ETF", "NYSE", "ETF"),
    ("VTI", "뱅가드 토탈 스톡마켓 ETF", "NYSE", "ETF"),
    ("IVV", "iShares 코어 S&P 500 ETF", "NYSE", "ETF"),
    ("DIA", "SPDR 다우존스 산업평균 ETF", "NYSE", "ETF"),
    ("IWM", "iShares 러셀 2000 ETF", "NYSE", "ETF"),
    ("EFA", "iShares MSCI EAFE ETF (선진국)", "NYSE", "ETF"),
    ("VEA", "뱅가드 FTSE 선진국 ETF", "NYSE", "ETF"),
    ("VWO", "뱅가드 FTSE 신흥국 ETF", "NYSE", "ETF"),
    ("AGG", "iShares 미국채권총합 ETF", "NYSE", "ETF"),
    ("BND", "뱅가드 토탈본드 ETF", "NASDAQ", "ETF"),
    ("TLT", "iShares 미국 20년+ 국채 ETF", "NASDAQ", "ETF"),
    ("GLD", "SPDR 금 ETF", "NYSE", "ETF"),
    ("SLV", "iShares 은 ETF", "NYSE", "ETF"),
    ("USO", "미국 원유 ETF", "NYSE", "ETF"),
    ("XLK", "테크놀로지 섹터 SPDR", "NYSE", "ETF"),
    ("XLF", "금융 섹터 SPDR", "NYSE", "ETF"),
    ("XLE", "에너지 섹터 SPDR", "NYSE", "ETF"),
    ("XLV", "헬스케어 섹터 SPDR", "NYSE", "ETF"),
    ("XLY", "임의소비재 섹터 SPDR", "NYSE", "ETF"),
    ("XLP", "필수소비재 섹터 SPDR", "NYSE", "ETF"),
    ("XLI", "산업재 섹터 SPDR", "NYSE", "ETF"),
    ("XLU", "유틸리티 섹터 SPDR", "NYSE", "ETF"),
    ("XLB", "소재 섹터 SPDR", "NYSE", "ETF"),
    ("XLRE", "부동산 섹터 SPDR", "NYSE", "ETF"),
    ("SCHD", "슈왑 미국 배당주 ETF", "NYSE", "ETF"),
    ("VYM", "뱅가드 고배당 ETF", "NYSE", "ETF"),
    ("ARKK", "ARK 이노베이션 ETF", "NYSE", "ETF"),
    ("SOXX", "iShares 반도체 ETF", "NASDAQ", "ETF"),
    ("SMH", "VanEck 반도체 ETF", "NASDAQ", "ETF"),
    ("IBIT", "iShares 비트코인 신탁 ETF", "NASDAQ", "ETF"),
    ("FBTC", "피델리티 비트코인 ETF", "NYSE", "ETF"),
]
